# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XXGPNSSgq2knnMusqPbqXlDwrkmcIG9L
"""

# ---------------------------
# 1) Imports
# ---------------------------
import streamlit as st
import pandas as pd
import numpy as np
import joblib
from pathlib import Path
from datetime import datetime, time

# ---------------------------
# 2) Basic page setup
# ---------------------------
st.set_page_config(page_title="NYC Taxi Fare", page_icon="🚕", layout="wide")
st.title("🚕 NYC Taxi Fare Estimator ")
st.write("Enter trip details and click **Predict fare**. If the trained model isn't found, we use a simple formula as a fallback.")

# ---------------------------
# 3) Config: model path + zone lists
# ---------------------------
MODEL_PATH = Path("models/model_v2.pkl")


pickup_zone_list  = ["Z4","Z12","Z41","Z48","Z68","Z79","Z87","Z100","Z132","Z138","Z158","Z170","Other"]
dropoff_zone_list = ["Z4","Z12","Z41","Z48","Z68","Z79","Z87","Z100","Z132","Z138","Z158","Z170","Other"]

# ---------------------------
# 4) Sidebar: about + status
# ---------------------------
model_available = MODEL_PATH.exists()
with st.sidebar:
    st.header("About this app")
    st.write("- Inputs → Output: distance, time/day, passengers, pickup + dropoff zones, rain → **total fare ($)**")
    if model_available:
        st.success("Model loaded")
    else:
        st.warning("No model file found — will use simple formula")

# ---------------------------
# 5) Inputs
# ---------------------------
c1, c2, c3 = st.columns(3)
with c1:
    distance_km = st.number_input("Trip distance (km)", min_value=0.1, max_value=80.0, value=5.0, step=0.1)
with c2:
    pickup_time = st.time_input("Pickup time", value=time(9, 0))
    pickup_hour = pickup_time.hour
with c3:
    weekday = st.selectbox("Pickup day", ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"])
    passenger_count = st.number_input("Passengers", min_value=1, max_value=6, value=1, step=1)
    
st.subheader("Zones & Weather")
pickup_zone  = st.selectbox("Pickup zone",  pickup_zone_list)
dropoff_zone = st.selectbox("Drop-off zone", dropoff_zone_list)
is_rain      = st.checkbox("Rainy day (simple flag)", value=False)

# derived flags
weekday_num = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].index(weekday)
is_weekend = 1 if weekday in ["Sat","Sun"] else 0
is_rush    = 1 if pickup_hour in [7,8,9,16,17,18,19] else 0

# ---------------------------
# 6) Fallback (transparent) formula
# ---------------------------
def baseline_fare(d_km, wknd, pax, rush, pu_zone, do_zone, rain):
    base_fee = 3.0
    per_km   = 1.8
    add = 0.0
    add += 1.0 if rush else 0.0
    add += 0.5 if wknd else 0.0
    add += 0.25 * max(0, pax - 1)
    add += 0.8 if rain else 0.0
    add += 1.0 if pu_zone != "Other" else 0.0
    add += 1.0 if do_zone != "Other" else 0.0
    return float(np.round(base_fee + per_km*d_km + add, 2))

# ---------------------------
# 7) Predict with the trained model
# ---------------------------
def model_predict():
    pipe = joblib.load(MODEL_PATH)
    X = pd.DataFrame([{
        "trip_distance_km": distance_km,
        "pickup_hour": pickup_hour,
        "passenger_count": passenger_count,
        "pickup_weekday": weekday_num,
        "is_weekend": is_weekend,
        "is_rush_hour": is_rush,
        "pickup_zone": pickup_zone,
        "dropoff_zone": dropoff_zone,
        "is_rain": int(is_rain)
    }])
    y = pipe.predict(X)[0]
    return float(np.round(y, 2))

# ---------------------------
# 8) Button and result
# ---------------------------
if st.button("🔮 Predict fare"):
    if model_available:
        try:
            y = model_predict()
            st.success(f"Estimated total fare: **${y:.2f}** (trained model)")
        except Exception:
            st.warning("Model failed to load — using simple formula.")
            y = baseline_fare(distance_km, is_weekend, passenger_count, is_rush, pickup_zone, dropoff_zone, is_rain)
            st.info(f"Baseline estimate: **${y:.2f}**")
    else:
        y = baseline_fare(distance_km, is_weekend, passenger_count, is_rush, pickup_zone, dropoff_zone, is_rain)
        st.info(f"Baseline estimate (no model yet): **${y:.2f}**")

    low, high = np.round(y*0.9, 2), np.round(y*1.1, 2)
    st.metric("Suggested range", f"${low:.2f} — ${high:.2f}")
    st.caption("Note: this is an estimate. Actual fares vary with traffic, tolls, surcharges, etc.")

# ---------------------------
# 9) Footer
# ---------------------------
st.write("")
st.caption("Built for a class project — simple features, small model, clear demo.")
